export const GIROS = [
  { value: 'parques industriales',          label: 'Parques industriales'              },
  { value: 'fábricas y plantas',            label: 'Fábricas y plantas de producción'  },
  { value: 'bodegas y almacenes',           label: 'Bodegas y almacenes'               },
  { value: 'plazas comerciales',            label: 'Plazas / centros comerciales'      },
  { value: 'fraccionamientos residenciales',label: 'Fraccionamientos residenciales'    },
  { value: 'edificios corporativos',        label: 'Edificios corporativos'            },
  { value: 'hoteles',                       label: 'Hoteles y centros de convenciones' },
  { value: 'hospitales privados',           label: 'Hospitales y clínicas privadas'    },
  { value: 'colegios y universidades',      label: 'Colegios y universidades'          },
  { value: 'bancos',                        label: 'Bancos e instituciones financieras'},
  { value: 'dependencias de gobierno',      label: 'Dependencias de gobierno'          },
  { value: 'supermercados',                 label: 'Supermercados y tiendas'           },
  { value: 'concesionarias',                label: 'Concesionarias de autos'           },
  { value: 'gasolineras',                   label: 'Gasolineras'                       },
  { value: 'joyerías',                      label: 'Joyerías y casas de cambio'        },
  { value: 'clubes y gimnasios',            label: 'Clubes deportivos y gimnasios'     },
  { value: 'centros de datos',              label: 'Centros de datos / TI'             },
  { value: 'transporte y logística',        label: 'Transporte y logística'            },
]
