export const PROFILES = [
  {
    key:   'industrial',
    icon:  '🏭',
    label: 'Industrial',
    giros: ['parques industriales', 'bodegas y almacenes', 'edificios corporativos'],
    color: '#f97316',
    bg:    '#fff7ed',
  },
  {
    key:   'corporativo',
    icon:  '🏢',
    label: 'Corporativo',
    giros: ['edificios corporativos', 'bancos', 'dependencias de gobierno'],
    color: '#4f46e5',
    bg:    '#eef2ff',
  },
  {
    key:   'comercial',
    icon:  '🛍️',
    label: 'Comercial',
    giros: ['plazas comerciales', 'hoteles', 'fraccionamientos residenciales'],
    color: '#0ea5e9',
    bg:    '#f0f9ff',
  },
  {
    key:   'salud',
    icon:  '🏥',
    label: 'Salud',
    giros: ['hospitales privados', 'colegios y universidades', 'dependencias de gobierno'],
    color: '#dc2626',
    bg:    '#fef2f2',
  },
  {
    key:   'gobierno',
    icon:  '🏛️',
    label: 'Gobierno',
    giros: ['dependencias de gobierno', 'bancos', 'edificios corporativos'],
    color: '#0891b2',
    bg:    '#ecfeff',
  },
  {
    key:   'residencial',
    icon:  '🏘️',
    label: 'Residencial',
    giros: ['fraccionamientos residenciales', 'hoteles', 'plazas comerciales'],
    color: '#7c3aed',
    bg:    '#f5f3ff',
  },
]
