export const PROFILES = [
  {
    key:   'industrial',
    icon:  '🏭',
    label: 'Industrial',
    giros: ['parques industriales', 'bodegas y almacenes', 'fábricas y plantas', 'transporte y logística'],
    color: '#f97316',
    bg:    '#fff7ed',
  },
  {
    key:   'corporativo',
    icon:  '🏢',
    label: 'Corporativo',
    giros: ['edificios corporativos', 'bancos', 'despachos profesionales'],
    color: '#4f46e5',
    bg:    '#eef2ff',
  },
  {
    key:   'comercial',
    icon:  '🛍️',
    label: 'Comercial',
    giros: ['plazas comerciales', 'supermercados', 'restaurantes y bares', 'concesionarias'],
    color: '#0ea5e9',
    bg:    '#f0f9ff',
  },
  {
    key:   'salud',
    icon:  '🏥',
    label: 'Salud',
    giros: ['hospitales privados', 'clínicas y consultorios', 'farmacias'],
    color: '#dc2626',
    bg:    '#fef2f2',
  },
  {
    key:   'gobierno',
    icon:  '🏛️',
    label: 'Gobierno',
    giros: ['dependencias de gobierno', 'aeropuertos y terminales', 'bancos'],
    color: '#0891b2',
    bg:    '#ecfeff',
  },
  {
    key:   'residencial',
    icon:  '🏘️',
    label: 'Residencial',
    giros: ['fraccionamientos residenciales', 'hoteles', 'clubes y gimnasios'],
    color: '#7c3aed',
    bg:    '#f5f3ff',
  },
  {
    key:   'entretenimiento',
    icon:  '🎭',
    label: 'Entrete.',
    giros: ['estadios y recintos', 'hoteles', 'restaurantes y bares'],
    color: '#db2777',
    bg:    '#fdf2f8',
  },
  {
    key:   'educacion',
    icon:  '🎓',
    label: 'Educación',
    giros: ['colegios y universidades', 'centros de datos', 'edificios corporativos'],
    color: '#65a30d',
    bg:    '#f7fee7',
  },
  {
    key:   'personalizado',
    icon:  '⭐',
    label: 'Personalizado',
    giros: ['gasolineras', 'restaurantes y bares', 'joyerías', 'supermercados', 'concesionarias', 'clubes y gimnasios', 'farmacias'],
    color: '#d97706',
    bg:    '#fffbeb',
  },
]
